### ISSUE TITLE
Textlänge der Meldungsbeschreibung erhöhen

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.frontend#129]
## Feature Branch
https://github.com/FixMyBerlin/fixmy.frontend/tree/fix/report-description_max-length

## TODOs

- [ ] ~~Maximalwert in config halten~~ nicht ins schema injizierbar

- [x] wert [hier](src/pages/Reports/pages/SubmitReport/pages/AdditionalDataForm.js:164) und [hier](https://github.com/FixMyBerlin/fixmy.frontend/blob/develop/src/pages/Reports/test/schemaValidation/newReport-jsonSchema.json#L15) hochsetzen

- [x] Hinweis an User

![GIF](https://user-images.githubusercontent.com/12786207/64858022-8598dd80-d626-11e9-8017-ee4f8ba0af0d.gif)

- [x] Testen
  - [x] Payload wird erfolgreich JSON-Schema validiert und in (geblockten/gemockten) Request gelegt
  - [x] Feld nimmt nicht mehr als den Maximalwert auf
