### ISSUE TITLE
Implement new Zeplin Layouts

### ISSUE THREAD

**Issue by geomC** [FixMyBerlin/fixmy.frontend#42]

**Comment by geomC** [comment]
## TODOs

List is derived from Zeplin and is propably not complete yet.

### Sidebar

- [ ] Adapt menu entry to contain a *Meldungen* group

### OverviewMap

- [ ] Fix height of mobile navBar
- [ ] adapt style of *Neue Meldung Button*
- [ ] indicate status / likes. needs clarification

### LocateMeMap

- [ ] update marker style
- [ ] update help text

### ReportDialog


#### /2 

- [ ] move *FahrradParkhaus* form to /4

#### /3

- [ ] update texts

#### FormProgressBar

- [ ] update to new nav, fix style bug
![image](https://user-images.githubusercontent.com/12786207/59975675-f21db680-95ba-11e9-96e5-3f13c1ef6525.png)

**Comment by hekele** [comment]
Bitte kein Gender-Sternchen sondern Doppeltpunkt verwenden. Also "Planner:innen" statt "Planner*innen".

**Comment by geomC** [comment]
Moved 
>  Adapt menu entry to contain a Meldungen group
To another issue
