### ISSUE TITLE
Move frontend related issues back to the frontend repo

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.frontend#536]
**Description of the desired change**

At some point we have decided to keep _all_ issues, even the ones related to this repository, in the [backend repo](https://github.com/FixMyBerlin/fixmy.platform/issues). The reason was Github lacked capabilities to show an overview about all issues of multiple repositories of our [organisation](https://github.com/FixMyBerlin) -- at least we thought that was the case.

What we did not know is that Github _does_ offer [project boards on an organisational level](https://github.blog/2016-10-27-introducing-projects-for-organizations/).

@cafca and me decided to bring the frontend-related issues back to this space. This will bring a couple of benefits:
* the context of an issue becomes clear -> it is the repo it is stored under
* we have less to explain to new DEVs because we stick to conventions

**Tasks**

- [ ] do research on how to automate  this
- [x] adapt [frontend contribution guide](https://github.com/FixMyBerlin/fixmy.frontend/blob/develop/CONTRIBUTING.md)
- [x] copy [issue and pr templates to here](https://github.com/FixMyBerlin/fixmy.platform/tree/master/.github)
- [x] adapt issue and pr templates for the backend repo (or even delete them, should be coordinated with @cafca )
- [x] make sure this repo has useful labels
