### ISSUE TITLE
Centralize Error Handling

### ISSUE THREAD

**Issue by s-pic** [FixMyBerlin/fixmy.frontend#561]
## Problem description

We use an `ErrorMessage` at various places, its state is managed by various components.
The error state should be shared across pages/components. This way centralized modules like [a new centralized api module](https://github.com/FixMyBerlin/fixmy.platform/issues/271) can easily cause error an error feedback.
The error state should be within the root of the redux state tree, the `ErrorMessage` should only be rendered once.

Not every error feedback to the user shall be managed with this, e.g. Form Errors should be managed within the component with custom UI elements.

## Context

This is part of the workload associated with FixMyBerlin/fixmy.platform#57

Also related issues:
https://github.com/FixMyBerlin/fixmy.platform/issues/23

## Tasks
- [x] Do some research about best practices

* https://github.com/reduxjs/redux/tree/master/examples/real-world
* https://itnext.io/react-redux-api-loading-errors-e783972c5424 **I will dig into this within the next days**. It uses [flux standard action](https://github.com/redux-utilities/flux-standard-action) which meets architecture as well as [reselect](https://github.com/reduxjs/reselect), which is something we could skip. **It also shows a patten how to manage the state of api requests in redux.**, which could help us with [another issue](https://github.com/FixMyBerlin/fixmy.platform/issues/271).

- [ ] Find a way to keep errorMessage as well as references to callback functions (invoked once the user acknoledges the error by clicking some sort of OK button) in the top of the store
- [ ] Render the errorMessage at thhe top of the component tree, wire it to the new state slice
- [ ] Make sure all errors are still handled, eventually with the help of [new ese tests](https://github.com/FixMyBerlin/fixmy.frontend/pull/323)
