### ISSUE TITLE
Umsetzung des Meldedialogs mit Material UI

### ISSUE THREAD

**Issue by cafca** [FixMyBerlin/fixmy.frontend#564]
**What's the problem you want solved?**

The 2020 design system is not applied to any of our features.

**Is there a solution you'd like to recommend?**

Start implementing the 2020 design system for the Meldedialog

**Tasks**

- [x] Setup Material UI as a dependency 
- [ ] Make sure it integrates with our build system

Refactor components to be built on top of Material UI and to conform with the 2020 design system

- [ ] Landing page
- [ ] Landing page desktop
- [ ] Overview map
- [ ] Overview map flyout
- [ ] Detail side bar

For the submission form:

- [ ] Location mode selection
- [ ] Locator
- [ ] Location Confirmation
- [ ] Bikestand count
- [ ] Photo upload & description
- [ ] Bike locker
- [ ] Thank you
- [ ] Newsletter confirmation
- [ ] New account confirmation

QA:

- [ ] Unit testing for select components
- [ ] Integration tests
