### ISSUE TITLE
Add Legend for accidents & cadastre for users

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.frontend#945]
**What's the problem you want solved?**
Users want to have an explanation for map features. 
There are currently accidents and the new cadastre layer which have no explanation yet. For this a new React component is needed which show's up on click a button.

**Is there a solution you'd like to recommend?**

**Tasks**

- [ ] Add open legend button
- [ ] Legend should open on click
- [ ] Legend should float on left side beneath search bar
- [ ] Legend should not overlay over map selector bar
- [ ] Legend should be scrollable when content would overflow
- [ ] Legend should close when clicking the close button
