### ISSUE TITLE
Legend should open on desktop automatically

### ISSUE THREAD

**Issue by ohrie** [FixMyBerlin/fixmy.frontend#983]
**What's the problem you want solved?**
The [`MapLegend`](https://github.com/FixMyBerlin/fixmy.frontend/blob/develop/src/components/MapLegend/Legend.tsx) should open automatically when open map, but only when on desktop.

Currently it does not open automatically, only when button MapLegendButton is clicked.

**Is there a solution you'd like to recommend?**

Use the [`showLegend`](https://github.com/FixMyBerlin/fixmy.frontend/blob/12cb07fa5e008538638a0ff1cdbec8b331ceb8b7/src/apps/Map/index.tsx#L123) state to enable, if it's an desktop. 

There is a JS function to check if user is on mobile or not: https://github.com/FixMyBerlin/fixmy.frontend/blob/3f19aed41666b3732c2c34f0d9dbbb1b921859a4/src/pages/KatasterKI/pages/Landing.js#L232

**Tasks**

- [ ] Check if mobile or desktop
- [ ] Change state if needed
- [ ] Ensure that feature works
